### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by chemzqm** [iamcco/coc-post#2]
* https://github.com/iamcco/coc-post/blob/ba14c7d5ccf6d287305593777b5e552b47d629d5/src/index.ts#L35 这里不需要判定 workspace.ready 因为 actiave 方法只会在 workspace ready 后调用
* https://github.com/iamcco/coc-post/blob/ba14c7d5ccf6d287305593777b5e552b47d629d5/src/index.ts#L37 https://github.com/iamcco/coc-post/blob/ba14c7d5ccf6d287305593777b5e552b47d629d5/src/index.ts#L55 https://github.com/iamcco/coc-post/blob/ba14c7d5ccf6d287305593777b5e552b47d629d5/src/index.ts#L56 返回的 disposable 没有加入 context.subscriptions

**Comment by iamcco** [comment]
感谢大佬 review，已经改了
